### ISSUE TITLE
When multiple species are display, they should be split by comma

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#112]
f more than one species are included in a dataset, all of them are displayed without a blank space in between (http://wwwdev.ebi.ac.uk/pride/archive?keyword=PXD010000).

![image](https://user-images.githubusercontent.com/52113/62858738-09dc0600-bcf3-11e9-8499-dffeba4be891.png)

I think (@ypriverol) we should limit the number of species that we show on the web to 4, if the user wants to see them all, he/she can go to the Dataset page.

**Comment by shabai517** [comment]
Fixed and please check.

**Comment by ypriverol** [comment]
I still see the error. 
<img width="1046" alt="Screen Shot 2019-08-15 at 18 19 43" src="https://user-images.githubusercontent.com/52113/63112950-66585300-bf89-11e9-880c-e0a9e319316c.png">

**Comment by shabai517** [comment]
Fixed
